#!/usr/bin/env bash
# Собрать dnsmasq LAN-конфиг из config.env (DHCP + reservation по MAC)
set -euo pipefail
# shellcheck disable=SC1091
: "${SYSTEMA_ROUTER_ROOT:=${PC_ROUTER_ROOT:-/home/admin/PC-Router}}"
source "$SYSTEMA_ROUTER_ROOT/scripts/lib/load-config.sh"
type netlog >/dev/null 2>&1 || netlog() { :; }

LAN_IF="${LAN_IF:-enp4s0}"
LAN_ADDR="${LAN_ADDR:-192.168.50.1}"
DHCP_RANGE_START="${DHCP_RANGE_START:-192.168.50.10}"
DHCP_RANGE_END="${DHCP_RANGE_END:-192.168.50.100}"
DHCP_LEASE="${DHCP_LEASE:-12h}"
DHCP_DNS="${DHCP_DNS:-8.8.8.8,1.1.1.1}"
OUT="${1:-/etc/dnsmasq.d/50-pc-router-lan.conf}"

{
  echo "# generated by PC-Router — do not edit by hand"
  echo "interface=${LAN_IF}"
  echo "bind-interfaces"
  echo "dhcp-authoritative"
  echo "dhcp-leasefile=/var/lib/misc/dnsmasq.leases"
  echo "dhcp-rapid-commit"
  echo "dhcp-range=${DHCP_RANGE_START},${DHCP_RANGE_END},255.255.255.0,${DHCP_LEASE}"
  echo "dhcp-option=3,${LAN_ADDR}"
  echo "dhcp-option=6,${DHCP_DNS}"
  IFS=';' read -ra LEASES <<<"${DEVICE_LEASES:-}"
  for item in "${LEASES[@]}"; do
    [[ -z "$item" ]] && continue
    IFS=',' read -r mac ip name <<<"$item"
    [[ -n "$mac" && -n "$ip" ]] || continue
    if [[ -n "${name:-}" ]]; then
      echo "dhcp-host=${mac},${ip},${name},infinite"
    else
      echo "dhcp-host=${mac},${ip},infinite"
    fi
  done
} >"$OUT"
chmod 644 "$OUT"
# убрать старое имя файла, если осталось с прошлых установок
rm -f /etc/dnsmasq.d/50-systema-cameras.conf
echo "wrote $OUT"
